version: '1'
env:
  - key: CI
    value: 'true'
build:
  nodeVersion: '22'
  commands:
    - npm ci
    - npm run build
distFolder: dist
php:
  version: '8.2'
runtime:
  imageId: node
  nodeVersion: '22'
